### ISSUE TITLE
Plugin Error: JSON Annotation Tool threw an uncaught NoSuchMethodError.

### ISSUE THREAD

**Issue by qianjin1111** [LiushuiXiaoxia/SerializedNameGen#2]
log如右：NoSuchMethodError: com.intellij.psi.PsiField.getAnnotations()[Lcom/intellij/psi/PsiAnnotation;

**Comment by qianjin1111** [comment]
As 2.3.3版本

**Comment by qianjin1111** [comment]
jdk1.8.0_112

**Comment by LiushuiXiaoxia** [comment]
额，Android Studio 2.3 版本没测过，
现在Android Studio的稳定版本为3.2.1了，你可以升级到这个版本看看。

下载地址 https://developer.android.com/studio/ 。
