### ISSUE TITLE
可否增加一个驼峰转下划线功能

### ISSUE THREAD

**Issue by hueyzhao** [LiushuiXiaoxia/SerializedNameGen#3]
java的命名规则习惯使用驼峰，json中的原始数据有时是下划线。
把json中的下划线属性转换成java中的驼峰属性需要写大量重复代码。
可否有空支持一个这样的功能，多谢！

**Comment by LiushuiXiaoxia** [comment]
好想法，有时间尝试一下。

**Comment by LiushuiXiaoxia** [comment]
已经添加此功能，可下载0.5版本

https://github.com/LiushuiXiaoxia/SerializedNameGen/tree/master/jars
